local f = CreateFrame("Frame", nil, UIParent)

local emotes = {
	"MOURN",
	"SNIFF",
	"LICK",
	"SNICKER",
	"GUFFAW",
	"GLOAT",
	"PITY",
	"VIOLIN",
	"BYE",
	"BITE",
	"CACKLE",
	"SHOO",
	"SLAP",
	"TEASE",
	"TAUNT",
	"MOCK",
	"MOO",
	"CHUCKLE",
	"BONK",
	"FLEX",
	"GRIN",
	"LAUGH",
	"MOON",
	"NO",
	"ROAR",
	"ROFL",
	"SCRATCH",
	"SIGH",
	"SNARL",
	"TAP",
	"INSULT",
	"BARK",
	"BECKON",
	"CALM",
	"CHICKEN",
	"COMFORT",
	"CUDDLE",
	"CURTSEY",
	"GIGGLE",
	"GROWL",
	"NOSEPICK",
	"RASP",
	"RUDE",
	"SMIRK",
	"SNUB",
	"SOOTHE",
	"THANK",
	"TICKLE",
	"VETO",
	"YAWN",
	"APOLOGIZE",
	"BEG",
	"CHEER",
	"CLAP",
	"CRY",
	"FART",
	"FROWN",
	"GASP",
	"HAIL",
	"NOD",
	"POINT",
	"SALUTE",
	"SHAKE",
	"SHRUG",
	"SURPRISED",
	"READY",
	--"POUNCE",
	--"CRACK",
	--"AGREE",
	--"AMAZE",
	--"ANGRY",
	--"APPLAUD",
	--"BASHFUL",
	--"BLEED",
	--"BLINK",
	--"BLUSH",
	--"COMMEND",
	--"TRAIN",
	--"RAISE",
	--"INTRODUCE",
	--"JK",
	--"LISTEN",
	--"TALK",
	--"TALKEX",
	--"TALKQ",
	--"BORED",
	--"BOUNCE",
	--"BRB",
	--"BOW",
	--"BURP",
	--"CONFUSED",
	--"CONGRATULATE",
	--"UNUSED",
	--"COUGH",
	--"COWER",
	--"CRINGE",
	--"CURIOUS",
	--"DANCE",
	--"DRINK",
	--"DROOL",
	--"EAT",
	--"EYE",
	--"FIDGET",
	--"GAZE",
	--"GLARE",
	--"GREET",
	--"GROAN",
	--"GROVEL",
	--"HAPPY",
	--"HELLO",
	"HUG",
	--"HUNGRY",
	--"KISS",
	--"KNEEL",
	--"LAYDOWN",
	--"MASSAGE",
	--"MOAN",
	--"PANIC",
	--"PEER",
	--"PLEAD",
	--"POKE",
	--"PRAY",
	--"SEXY",
	--"SHOUT",
	--"SHY",
	--"SIT",
	--"SLEEP",
	--"SPIT",
	--"STARE",
	--"SURRENDER",
	--"THREATEN",
	--"TIRED",
	--"VICTORY",
	--"WAVE",
	--"WELCOME",
	--"WHINE",
	--"WHISTLE",
	--"WORK",
	--"BOGGLE",
	--"COLD",
	--"DUCK",
	--"LOST",
	--"PONDER",
	--"PRAISE",
	--"PURR",
	--"PUZZLE",
	--"SHIMMY",
	--"SHIVER",
	--"STINK",
	--"THIRSTY",
	--"STAND",
	--"SMILE",
	--"SCARED",
	--"FLOP",
	--"LOVE",
}

local function GetRandomEmote()
	return emotes[math.random(1, #(emotes))]
end

--local function OnEvent(self, event, ...)
local function OnEvent(self, ...)
	--local _, subEvent, srcGUID, srcName, srcFlags, dstGUID, dstName, dstFlags = ...
	local _, subEvent, _, srcGUID, srcName, srcFlags, _, dstGUID, dstName, dstFlags, _ = CombatLogGetCurrentEventInfo()
	if subEvent == "PARTY_KILL" then
		if srcGUID == UnitGUID("player") and ( bit.band(dstFlags, COMBATLOG_OBJECT_REACTION_HOSTILE) > 0 and bit.band(dstFlags, COMBATLOG_OBJECT_TYPE_PLAYER) > 0 ) and not ( bit.band(dstFlags, COMBATLOG_OBJECT_AFFILIATION_RAID) > 0 or bit.band(dstFlags, COMBATLOG_OBJECT_AFFILIATION_PARTY) > 0 or bit.band(dstFlags, COMBATLOG_OBJECT_AFFILIATION_MINE) > 0 ) then
				DoEmote(GetRandomEmote(), dstName)
				--TakeScreenshot() -- Take a picture to commemorate the occassion
		end
	end
end

f:RegisterEvent("COMBAT_LOG_EVENT_UNFILTERED")

f:SetScript("OnEvent", OnEvent)
